server:
  port: 8888
spring:
  application:
    name: CloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/aaliagab/WasteManagementConfigurations.git"
          clone-on-start: true
